### PR TITLE
Aadit's Page

### PR DESCRIPTION
**Pull request by Aadit-Ambadkar**

### CODE REVIEW

**Comment by kjschmidt913** [comment]
Your page looks great! I love the fun background and your about section. Great use of bootstrap classes for styling! I'm glad you were able to look through the docs and become familiar with some of the classes.

Just a few things:
1. Could you change the link on your projects page to direct to `students/aadit/index.html`? Right now it's missing the `index.html` part of the link and throwing an error. This is also happening on the link you added to `student-list.html` so please fix that one as well.
2. Lines 47-53 of `index.html` have the styling within the html tag. I would discourage putting styles there. I would either make a class and put that styling in the css file so that all of your custom css is in one place, or I would use the [bootstrap text color classes](https://getbootstrap.com/docs/5.0/utilities/colors/). I think you could achieve the effect you're using with the bootstrap classes (`text-secondary`, `text-muted`, `text-light`) so I would recommend trying that approach first.
3. I see that your custom css includes styling that could potentially be simplified with bootstrap classes ([spacing](https://getbootstrap.com/docs/5.0/utilities/spacing/) and [position](https://getbootstrap.com/docs/5.0/utilities/position/) are what caught my eye). Explore and play around with bootstrap classes to see if you can get rid of most, if not all, of your custom css!
4. The `script` tags on lines 105 and 106 of `index.html` should go at the very end of the `body` tag (the line right before `</body>`) so please move those down.
5. I had everyone add at least 2 [bootstrap components](https://getbootstrap.com/docs/5.0/components/) just to get more familiar with bootstrap. Take your time and play around with getting these on your page! It doesn't need to look professional and will probably look a bit silly. Don't worry, there's a task later for cleaning up your page and taking these out. This part of the assignment is for you to become more familiar with bootstrap and what all it can do :)
6. Could you add your goals and interests to your page? I know you've discussed your interests a bit already in the "about" section, so at least adding a goals section would be enough if you don't want to add both.

Overall, you're off to a great start! Let me know when you have a chance to submit changes and I'll take another look. You can push them to your branch and they'll show up here.

**Comment by Aadit-Ambadkar** [comment]
**not done yet**

**Comment by Aadit-Ambadkar** [comment]
I'm done!

**Comment by kjschmidt913** [comment]
This looks great!! I'm glad you tried out the bootstrap classes even though the custom css is what worked better. Always good to see if you can simplify. Thanks for making these changes. I'll merge them in!

**Pull request merged**
